import { createStyle } from "@in/style";

export const PresentationToggleStyle = {
  item: createStyle({
    base: [
      "group",
      "relative",
      "cursor-pointer",
      "flex items-center justify-center",
      "h-10 w-10",
      "aspect-square",
      "rounded-full",
      "bg-(--surface)",
      "text-(--primary)",
      "shadow-prime",
      "transition-transform duration-200",
      "hover:scale-110",
      "active:scale-95",
      {
        web: {
          position: "relative",
          cursor: "pointer",
          display: "flex",
          alignItems: "center",
          justifyContent: "center",
          height: "2.5rem",
          width: "2.5rem",
          aspectRatio: "1/1",
          borderRadius: "50%",
          backgroundColor: "var(--surface)",
          color: "var(--primary)",
          boxShadow: "var(--shadow-prime)",
          transition: "transform 0.2s ease-in-out",
        },
      },
    ],
  }),
  icon: createStyle({
    base: [
      "flex",
      "items-center",
      "justify-center",
      "h-6 w-6",
      "text-(--primary)",
      {
        web: {
          display: "flex",
          alignItems: "center",
          justifyContent: "center",
          height: "1.5rem",
          width: "1.5rem",
          color: "var(--primary)",
        },
      },
    ],
  }),
  label: createStyle({
    base: [
      "pointer-events-none",
      "absolute",
      "z-[9999]",
      "top-full",
      "mt-1",
      "left-1/2",
      "-translate-x-1/2",
      "px-2 py-0.5",
      "whitespace-nowrap",
      "rounded-md",
      "bg-(--surface)",
      "text-(--primary)",
      "text-xs",
      "shadow-prime",
      "opacity-0",
      "group-hover:opacity-100",
      "transition-opacity duration-150",
      {
        web: {
          pointerEvents: "none",
          position: "absolute",
          zIndex: 9999,
          top: "100%",
          marginTop: "0.25rem",
          left: "50%",
          transform: "translateX(-50%)",
          padding: "0.125rem 0.5rem",
          whiteSpace: "nowrap",
          borderRadius: "0.375rem",
          backgroundColor: "var(--surface)",
          color: "var(--primary)",
          fontSize: "0.75rem",
          boxShadow: "var(--shadow-prime)",
          opacity: 0,
          transition: "opacity 0.15s ease-in-out",
        },
      },
    ],
  }),
};


