// AUTO-GENERATED by modules/in-widget/scripts/generate-icon-variants.ts – DO NOT EDIT
// Last updated: 2025-10-20T03:42:18.690Z

export type IconVariant =
  | 'APIIcon'
  | 'ArrowBottomIcon'
  | 'ArrowsHorizontalLineIcon'
  | 'ArrowSwapIcon'
  | 'ArrowUpIcon'
  | 'AxesGizmoIcon'
  | 'BrandIcon'
  | 'BubbleGridIcon'
  | 'CaretDownPrimeIcon'
  | 'CaretLeftPrimeIcon'
  | 'CaretRightPrimeIcon'
  | 'CaretUpPrimeIcon'
  | 'CheckIcon'
  | 'ClockIcon'
  | 'CodeIcon'
  | 'CommentIcon'
  | 'CrosshairIcon'
  | 'CubeGizmoIcon'
  | 'DarkModeIcon'
  | 'DBIcon'
  | 'DirectionRightIcon'
  | 'DotSixIcon'
  | 'FileIcon'
  | 'FlowVisualizerIcon'
  | 'FolderNotchIcon'
  | 'FolderNotchOpenIcon'
  | 'FunnelIcon'
  | 'GoogleIcon'
  | 'InSpatialIcon'
  | 'LeaderboardIcon'
  | 'LightModeIcon'
  | 'LoadingIcon'
  | 'MaximizeIcon'
  | 'MinimizeIcon'
  | 'MinusIcon'
  | 'OrbitIcon'
  | 'PanIcon'
  | 'PencilIcon'
  | 'PlayIcon'
  | 'PlusIcon'
  | 'PlusPrimeIcon'
  | 'RedoIcon'
  | 'RoundIcon'
  | 'SecurityKeyIcon'
  | 'SelectIcon'
  | 'SettingsIcon'
  | 'ShapeIcon'
  | 'ShareIIIcon'
  | 'UndoIcon'
  | 'XPrimeIcon';

export const ICON_VARIANTS: readonly IconVariant[] = [
  'APIIcon',
  'ArrowBottomIcon',
  'ArrowsHorizontalLineIcon',
  'ArrowSwapIcon',
  'ArrowUpIcon',
  'AxesGizmoIcon',
  'BrandIcon',
  'BubbleGridIcon',
  'CaretDownPrimeIcon',
  'CaretLeftPrimeIcon',
  'CaretRightPrimeIcon',
  'CaretUpPrimeIcon',
  'CheckIcon',
  'ClockIcon',
  'CodeIcon',
  'CommentIcon',
  'CrosshairIcon',
  'CubeGizmoIcon',
  'DarkModeIcon',
  'DBIcon',
  'DirectionRightIcon',
  'DotSixIcon',
  'FileIcon',
  'FlowVisualizerIcon',
  'FolderNotchIcon',
  'FolderNotchOpenIcon',
  'FunnelIcon',
  'GoogleIcon',
  'InSpatialIcon',
  'LeaderboardIcon',
  'LightModeIcon',
  'LoadingIcon',
  'MaximizeIcon',
  'MinimizeIcon',
  'MinusIcon',
  'OrbitIcon',
  'PanIcon',
  'PencilIcon',
  'PlayIcon',
  'PlusIcon',
  'PlusPrimeIcon',
  'RedoIcon',
  'RoundIcon',
  'SecurityKeyIcon',
  'SelectIcon',
  'SettingsIcon',
  'ShapeIcon',
  'ShareIIIcon',
  'UndoIcon',
  'XPrimeIcon',
] as const;
