// Auto-generated by InSpatial Serve – DO NOT EDIT
// This file is regenerated on each build when extensions change
import type { ExtensionTriggerTypes as T0 } from "@in/route/types.d.ts";
import type { ExtensionTriggerTypes as T1 } from "@in/cloud/types.d.ts";

declare global {
  namespace InSpatial {
    interface ExtensionTriggers extends T0, T1 { }
  }
}
export {};
